### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by reitermarkus**

### CODE REVIEW

**Comment by reitermarkus** [comment]
@jawshooah, ping.

**Comment by jawshooah** [comment]
Looks like adding `gem update --system` to `.travis.yml` should fix the `rainbow` build error on 2.3 ([source](https://github.com/sickill/rainbow/issues/49#issuecomment-274714272)). Mind trying that before we merge?

**Comment by jawshooah** [comment]
Also, seeing as I've had next to no time to do OSS things for a while now (though hopefully that will change in a month or two), would you like to be added as an owner of the `rubocop-cask` gem? That way you won't be blocked on me to publish updates.

**Comment by reitermarkus** [comment]
> would you like to be added as an owner of the `rubocop-cask` gem? 

Yes, seems like a good idea.

**Comment by reitermarkus** [comment]
@jawshooah, seems like `gem update --system` did the trick.

**Comment by jawshooah** [comment]
@reitermarkus Merged and published as 0.11.0.

Before I can add you as an owner of the gem, you need to [create an account](https://rubygems.org/sign_up) on rubygems.org. Once you've done that, please let me know what email address you used so I can add you as an owner.

**Comment by reitermarkus** [comment]
My email is me@reitermark.us. Also, I don't have push access to this repo yet.

**Comment by jawshooah** [comment]
Whoops, looks like I forgot to give caskroom/maintainers write access to this repo when I created it 😨 

Anyway, you are now an owner of the `rubocop-cask` gem and have write access to this repo.

To cut a new release:
- Update the version in `lib/rubocop/cask/version.rb`
- `bundle exec rake build` to run tests and generate the changelog
- `git add lib/rubocop/cask/version.rb CHANGELOG.md`
- `bundle exec rake release`

**Pull request merged**
